site_name: CBMERJ - Grupo 7
theme:
  name: material
  language: pt-BR
  features: 
     - toc.integrate
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro

    - scheme: slate 
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro

extra:
  extra_css:
  - style.css

copyright: |
  &copy; 2024 - IHC