repo_url: https://github.com/Interacao-Humano-Computador/2024.1-CBMERJ/tree/main
site_name: CBMERJ - Grupo 7
theme:
  name: material
  language: pt-BR
  features: 
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro

    - scheme: slate 
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro
extra:
  extra_css:
  - style.css
copyright: |
  &copy; 2024 - IHC

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

# Page tree
nav: 
  - Início: index.md
  - Atas:
      - Ata 1: atas/ata_1.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao_1.md
  - Planejamento:
      - Heatmap: planejamento/heatmap.md
      - Cronograma: planejamento/cronograma.md
      - Cronograma Realizado: planejamento/CronogramaRealizado.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Processo de Design: planejamento/processo-de-design.md
      - Sites Avaliados: planejamento/sites-avaliados.md
      - Site Escolhido: planejamento/site-escolhido.md
  - Análise de Requisitos:
      - Análise de tarefas: analise_requisitos/analise_tarefas.md
      - Aspectos Éticos: analise_requisitos/file_name.md
      - Perfil do Usuário: analise_requisitos/file_name.md
